title: Sushmitha R
logo: /assets/logo.png
##description: Minimal is a theme for GitHub Pages.
email: rsushmitha910@gmail.com
lindkenIn: www.linkedin.com/in/sushmitha-r777
Portfolio: github.com/Sushmitha910/DataScientist

##show_downloads: true
##google_analytics:
theme: jekyll-theme-minimal
