title: Sushmitha R
logo: /assets/logo.png
description: rsushmitha910@gmail.com
www.linkedin.com/in/sushmitha-r777
github.com/Sushmitha910/DataScientist

##show_downloads: true
##google_analytics:
theme: jekyll-theme-minimal
